decoration {
    rounding = 5
    # Change transparency of focused and unfocused windows
    dim_inactive = true
    dim_special = 0.2
    blur {
      enabled = false
    }   
    shadow {
    } 
    # battery life^

}
